baseURL: "https://example.com/"
languageCode: "en"
title: "Example site"

disableKinds: []
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: false
    renderHooks:
      link:
        useEmbedded: auto

outputs:
  home:
    - html
    - rss
    - sitemap
